### ISSUE TITLE
Option to create custom comparison groups

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/institutional-assessment-dashboard#112]

**Comment by Shelmith-Kariuki** [comment]
Improve UX for country selection: Being able to write the country to select? Being able to quickly recover that? Search function? (New issue: #174 )

**Comment by Shelmith-Kariuki** [comment]
Function for selecting comparator group as intersection of groups (E.g., region w/income group) (New issue: #112)

**Comment by Shelmith-Kariuki** [comment]
- [ ] In the “Country Benchmarking” tab, the selected “base country” could be colored blue (like the report button). Also, selected countries with check could also be colored, like light blue or something?

(New issue: #175)
