### ISSUE TITLE
DRC missing code

### ISSUE THREAD

**Issue by galileukim** [worldbank/institutional-assessment-dashboard#139]
DRC (iso 3 code: COD) is missing in the dashboard. This seems to be an issue close to Romania (ROM, ROU), with the extra component of being careful with Congo, Rep. (iso 3 code: COG). There’s data for DRC in the API as well as in the manual data, meaning some place along the code we’re loosing it.

In addition, and maybe related, DRC appears on the dashboard as “Congo, Rep., Dem. Rep.” again. So let’s make sure that is fixed too.

**Comment by kannanv93** [comment]
The issue has been fixed by replacing merged_for_residuals.rds with merged_for_residuals-v2.dta provided by Eric
