### ISSUE TITLE
Improve quality of data downloads (focus on stata format)

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#141]
ALL FORMATS
- [x] Ensure that countries have at least official world bank country names and official world bank country codes

STATA SPECIFIC
- [x] Ensure that variables such as year are numeric and not strings
- [x] Add "labels"

**Comment by kannanv93** [comment]
@erwbg : Aren't we using the standardized country names now? Refer [Country_name_list.csv](https://github.com/worldbank/institutional-assessment-dashboard/blob/dev2/app/data/Country_name_list.csv) file for WB standardization.

**Comment by kannanv93** [comment]
@erwbg  Can you please explain what you mean by add "Labels" ?

**Comment by kannanv93** [comment]
Issue has been fixed.

**Comment by kannanv93** [comment]
Issue was due to translatecharutf8. Fixed this issue.
