### ISSUE TITLE
Produce graphs in Excel format

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#142]
We can discuss and decide whether we use them only in the .docx Report. But we should be able to produce the figures in the report as Excel figures, and have an additional .xslx file where each sheet has each figure and underlying data.

**Comment by kannanv93** [comment]
@erwbg: Currently packages like XLSX or OpenXLSX export the figures to excel directly. Those charts are un-editable. Can you please confirm if this is what is needed?
