### ISSUE TITLE
Allow users to download a PPT in addition to the .docx Report

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#143]
As in a PPT version of the .docx report. Let us first start with a title slide, and intro slide, and then one slide for each graph/family.

See: https://bookdown.org/yihui/rmarkdown/powerpoint-presentation.html

**Comment by kannanv93** [comment]
@erwbg  Can you please share a PowerPoint template that I can refer to?

**Comment by kannanv93** [comment]
<img width="940" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/c8d5e903-d127-4546-99c2-8f3c0d9b8a8b">

Made the PPT wider.
