### ISSUE TITLE
Multiple bugs around "Ranking"

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#144]
- [x] In the data tab, it is clear that the RANK is estimated including the “country groups”. This is a mistake, the rank should be based only on countries.
- [x] Also when looking at the data tab, there are cases where country groups == 2 if group, and country a 1, instead of 1 and 0. That has to be fixed.
- [x] Graph that "shows rank instead of value" displays wrong values when hovering. See image. A rank can't be e.g., 244.
![image](https://user-images.githubusercontent.com/127211275/232860167-b1a86b06-ec00-44c7-a556-1be4906fa876.png)

**Comment by kannanv93** [comment]
Issue 1&2 have been resolved. Ensured that ranks are generated separately for countries and country groups.  
Use the country_group = 0 filter to get ranking for countries and country_group = 1 to get country_group ranking.

**Comment by kannanv93** [comment]
Fixed all the issues

**Comment by kannanv93** [comment]
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/3ee569b4-7bef-485d-b374-e4f35fb86352)
Fixed this issue using min_rank instead of rank function.  min_rank function assigns the same rank to tied values, and the next value receives a rank one higher.

**Comment by kannanv93** [comment]
Reference: In the above case, estonia, latvia, lithuania,slovenia all have a rank = 1.

<img width="917" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/a4556a0f-4887-4eec-935f-1499181e2559">

Fixed plot
<img width="1085" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/a30adb36-c611-42e1-b8c5-52bdc1f8fea7">
