### ISSUE TITLE
Fix the Indicator Table in Appendix B - Indicator definitions of the .docx report

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#145]
There is a bug/formatting error in the Anticorruption, transparency and accountability family.

**Comment by kannanv93** [comment]
Issue occurred due to the presence of white space in the raw text. Removed whitespaces and issue was resolved.

**Comment by kannanv93** [comment]
<img width="454" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/7840d90b-c1ec-40d6-aec6-96f63da9fc76">
Issue Fixed
