### ISSUE TITLE
Add new tab with "Publications" to show 'reports that use CLIAR'

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#147]
The idea here is to have a "repository" of reports that have used CLIAR as examples.

If possible, I'd like to follow this model: https://www.aiddata.org/publications

- To keep it simple, each "report" should be simply the PDF that we store locally (no need for additional page, and to avoid broken links for now, let's just add the PDF).
- I like the "search by keyword"
- for the "titles" I say we follow the aiddata structure (with a picture), but in our case an example would be:
Country Economic Memorandum (CEM)
Croatia CEM: Blah
Author 1 (POV ECA), Author 2 (GOV ECA)
2022

-In our CLIAR one drive folder, we have a reports folder. Let's start this by using the Croatia CEM and the Mozambique CCIA to do the draft zero.

**Comment by Shelmith-Kariuki** [comment]
Hi @erwbg 

I have already developed this: 
![Screen Shot 2023-07-20 at 2 39 34 PM](https://github.com/worldbank/institutional-assessment-dashboard/assets/37449624/31f6fd63-e471-4352-9ef8-3f08d11dc3b6)

**Comment by Shelmith-Kariuki** [comment]
ToDo: Create an excel sheet on OneDrive that contains metadata to be used in the publications tab.

**Comment by Shelmith-Kariuki** [comment]
Hi @erwbg , 

I've added **_publicationsList.xlsx_** to the data folder in OneDrive

**Comment by Shelmith-Kariuki** [comment]
For the "showcasing ongoing work" part, please give me an example of a team that is currently working with CLIAR and how they are using it.

**Comment by kannanv93** [comment]
@erwbg Please check and confirm
