### ISSUE TITLE
Fix bug on Report: download of "show comparator countries" graphs

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#149]
When choosing the option "show comparator countries" and the downloading the report, the report only downloads the overview graphs with comparators. Double-check and fix that.

*OR*

**Consider the option of a report with "all" the possible graphs.** THOUGHTS?

**Comment by kannanv93** [comment]
Fixed Issue
<img width="468" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/595cf755-4f69-47cd-8c1a-24335ccc82c7">
