### ISSUE TITLE
Allow users to choose benchmarking thresholds

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#153]
Right now, we have the following (default) thresholds: 0-25, 25-50, and 50 above.

This should be the default, but we should add the option for users to also choose the following thresholds: 0-33, 33-66, and 66 above.

**Comment by kannanv93** [comment]
Added a range slider to select thresholds dynamically.

<img width="1252" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/8cc0b7ec-1164-4a91-bbee-0cce7141b9d4">

**Comment by kannanv93** [comment]
<img width="1290" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/b96a9371-a70a-4909-8b65-2c61e9dadd58">
Changed from RangeSlider to Option Select
