### ISSUE TITLE
Use country groups in graphs legends and reports, in addition to list of countries

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#154]
Issue: when users currently select a country-group, say "High-Income Countries" (and doesn't alter the list), all the analysis/graphs/legends "ignore" that decision and simply describe the list of countries. This is confusing, as people want to read "High-Income Countries" and then, a description saying "which includes Country A, B, etc."

Task: when a country-group is selected and not modified (or, more generally, when the selection of countries, matches a given country group), add the name of that country-group before the list of countries. This applies to the report and to graph notes. Double check where else it could apply.

**Comment by Shelmith-Kariuki** [comment]
Hi @erwbg , 

Let's handle this once we re-design the grouping methodology.
