### ISSUE TITLE
De-bug the code that assigns global rankings

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#157]
- [x] We need to ensure that the global ranking does not include the "country groups" and only includes countries. This not only implies ensuring the ranking works correctly, but also that the data displays correctly. Currently, when visualizing the rank, both countries and country groups are displayed, both with "country_group=1"
- [x] We need to ensure that global rankings properly take into account ties. Example, if 2 countries are tied with the same score for rank 1, the next country should be ranked 3 (not 2).

**Comment by kannanv93** [comment]
<img width="589" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/3b3bd711-b659-4b02-b432-e260645f6853">
Fixed the issue
