### ISSUE TITLE
app is not reproducible locally, due to inconsistencies in data

### ISSUE THREAD

**Issue by galileukim** [worldbank/institutional-assessment-dashboard#160]
When deploying locally, due to inconsistency in data inputs, I receive the following error. Verifying the `master.R` file, I also noticed that data inputs are not consistently labelled across scripts. Let's try to fix that.

`Warning: Error in select: Problem while evaluating `all_of(vars_table)`.
Caused by error in `all_of()`:
! Can't subset elements that don't exist.
✖ Elements `governanceofstateownedenterprise`, `useofcommandcontrolregulation`, and `pricecontrols` don't exist.`

**Comment by kannanv93** [comment]
With New Data shared, the app was reproducible locally. We can re-open this if others have any difficulties
