### ISSUE TITLE
for each chunk of code, at least a one-liner explaining what kinds of transformations are happening. - Abby, Kannan, Gali.

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#172]

**Comment by galileukim** [comment]
@erwbg let me provide a bit more detail here:

1. Objective
Improve documentation of data (a) source and (b) transformation, through in-code comments in the bookdown file.

2. Outputs
For each step of our pipeline, provide documentation on the following: (a) how was the data downloaded/obtained (e.g., EFI 360 or legacy indicators), including URLs where relevant; (b) transformation of indicators, whether it is reversal, normalizing or rescaling, and (c) where relevant, outline data requirements. For example, some steps in the outline require the country group list (in Excel).
