### ISSUE TITLE
Create a substantive "ordering" of families and indicators within families

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#173]
The idea is that the order of families/indicators helps the narrative/thinking about it. So it shouldn't be alphabetical nor random, but rather guided by our own subtantive thinking.

@erwbg will work on the actual order, and @Shel will help implement.

There's also an additional point to consider, about adding visualizations to help this. To be discussed.

To create:
- [x] ordering of families
- [x] ordering of indicators within each family
- [x] [tbd] create some sort of brackets "}" or some other visualization to "bucket/group" similar indicators within each family

**Comment by galileukim** [comment]
To accomplish this, we could use the following package, which helped me a lot of [reordering of bar graphs within facets](https://search.r-project.org/CRAN/refmans/tidytext/html/reorder_within.html)

**Comment by Shelmith-Kariuki** [comment]
Hi @erwbg , 

This is what I have done. I've added a temporary rank_id variable to the dataset that ranks indicators within family. I then added an input field where users can click if they want to see the indicators ranked via the id. 
When that input field is not, clicked, indicators are ordered as before (see the '
Use preset ranking order' input field below) ... 

![Screen Shot 2023-09-12 at 9 21 46 AM](https://github.com/worldbank/institutional-assessment-dashboard/assets/37449624/6f08991a-786e-4736-8f1b-ca0917a19a0a)

When the field is clicked, the indicators are ranked via our order

![Screen Shot 2023-09-12 at 9 16 20 AM](https://github.com/worldbank/institutional-assessment-dashboard/assets/37449624/2dc8df55-945a-4386-b0e7-77bed5a4ea21)

The rank id will need to be attached to db_variables. 

Please let me know if this is what you had in mind.

**Comment by kannanv93** [comment]
@erwbg  : I introduced Family Order and implemented this. You should be able to see the ordering the https://datanalytics.worldbank.org/cliar_uat/ version. Please let me know if you don't see the ordering.

**Comment by kannanv93** [comment]
@erwbg : regarding "Rank indicators from best to worst", how to handle the ordering in regional benchmarking ? Right now we have the same placeholder for country and regional benchmarking. In regional benchmarking, sorting based on CTF would be difficult. Please let me know how to handle.

**Comment by kannanv93** [comment]
Fixed issue.

**Comment by galileukim** [comment]
@erwbg this sounds very complex to implement in `ggplot`. off the top of my head, `ggplot` is not friendly in reordering axis labels, in particular when these are dynamic across country-level datasets. maybe the function `reorder_within` from the `tidytext` package can help, but this will be costly to implement.

**Comment by kannanv93** [comment]
Lebanon vs HIC issue is fixed.

**Comment by kannanv93** [comment]
@erwbg : Is the below comment still valid given that we have a fixed ordering now

_ It would be great if we can add the following feature: rank from best to worse, but by groups.

That is: first rank from strong to emerging to weak, and then, within each group, from highest to lowest CTF.

See the Uruguay vs OECD example. we want to see all green "together", all yellow together, and then all red together.

_

**Comment by galileukim** [comment]
@kannanv93, please find the references for the `reorder_within` function here: https://juliasilge.github.io/tidytext/reference/reorder_within.html.

The only thing we would have to skip is the `facet_wrap` command.

**Comment by kannanv93** [comment]
<img width="1281" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/90bd8250-90de-4561-a5d8-8e5d756f21a2">

Fixed issue
