### ISSUE TITLE
Bug in indicators_map.rds

### ISSUE THREAD

**Issue by Shelmith-Kariuki** [worldbank/institutional-assessment-dashboard#178]

**Comment by Shelmith-Kariuki** [comment]
Hi, 

There seems to be a bug in how the indicators_map.rds data is being generated and saved. Please see the screenshot attached. 



![Image](https://github.com/worldbank/institutional-assessment-dashboard/assets/37449624/bfc40d74-475f-4916-93be-b6778b0896b3)

**Comment by galileukim** [comment]
Hi @Shelmith-Kariuki, the most likely case is that in the `map.Rmd` (`code` folder) script did not compile correctly. Could you make sure that you have correctly generated the `world_map` object? Otherwise it's probably just generating an `rds` object with the `map` funciton from `purrr`.

**Comment by Shelmith-Kariuki** [comment]
Hi @galileukim , 

Thanks. Will do

**Comment by Shelmith-Kariuki** [comment]
Hi, 

I have re-downloaded the data and successfully viewed the app locally. I'm also receiving the error that @gali mentioned. I will close this issue and proceed to open a new one.
