### ISSUE TITLE
Bug in output$map

### ISSUE THREAD

**Issue by Shelmith-Kariuki** [worldbank/institutional-assessment-dashboard#181]

**Comment by galileukim** [comment]
@Shelmith-Kariuki I have introduced a fix to address this map bug in our data ETL in our Pull Request for the data-etl branch. I would need someone to review the changes I have introduced to merge into main. Could you please review the Pull Request and make sure it runs locally?

**Comment by Shelmith-Kariuki** [comment]
@galileukim the fix didn't clear the bug. I have sorted the issue based on the info shared here: https://github.com/r-spatial/sf/issues/584. I have committed and pushed the edit. Please pull and review.

![Image](https://github.com/worldbank/institutional-assessment-dashboard/assets/37449624/126c797e-7235-4a21-9659-241daba1a5d5)
