### ISSUE TITLE
Update dashboard text

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#187]
@kannanv93: in the latest version that you deployed, can you kindly include the following edits to the text?

I drafted in track changes, hoping it's easier. We'll get another round of edits as we complete the methological note --so if there's a better way to provide edits on the text for next time, would be great to think about that as well.

[Dashboard Text.docx](https://github.com/worldbank/institutional-assessment-dashboard/files/12591485/Dashboard.Text.docx)

happy to discuss on a call if easier

**Comment by kannanv93** [comment]
Updated
