### ISSUE TITLE
UAT - Maps Error

### ISSUE THREAD

**Issue by kannanv93** [worldbank/institutional-assessment-dashboard#192]
<img width="1153" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/7575e72c-aaab-40b9-abe3-88906a4614fc">

- 
- 

- [ ] #205
- [x] Original Indicators not working

**Comment by galileukim** [comment]
Just to complement this @kannanv93 and @Shelmith-Kariuki, it seems that the family averages in particular are throwing issues -- not individual indicators.

**Comment by kannanv93** [comment]
@erwbg @galileukim  : Can you please confirm if we need to show timetrends for average too? Right now, we compute averages in CTF code and we add family averages to the CTF data. We do not compute averages on the raw data. We might have to make some modifications and compute family averages on raw data too.

**Comment by galileukim** [comment]
We need to review this carefully, to distinguish this exercise from the CTF based family scores. @Shelmith-Kariuki should explain to us exactly how she calculated the family scores, so we can distinguish that from the raw data-based scores.

**Comment by kannanv93** [comment]
<img width="909" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/faaeb69b-e611-440b-ab4d-5778408ed69f">
 For reference

**Comment by kannanv93** [comment]
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/db5cf06a-eef6-4ed7-adf0-5049f06e8e23)

**Comment by kannanv93** [comment]
Have to Fix Averages by taking Min - max values
