### ISSUE TITLE
UAT - Time Trends

### ISSUE THREAD

**Issue by galileukim** [worldbank/institutional-assessment-dashboard#194]
There are issues with the time trends. The app is not displaying the institutional family averages correctly, and for some (other) indicators, the app crashes.

**Comment by kannanv93** [comment]
Updated code to not show Averages in Time Trends. I am not sure if we need to have averages in time trends.

**Comment by galileukim** [comment]
Thank you for finding this rabbit hole. Let's discuss in the technical meeting how to compute this -- related to another issue you have raised.

**Comment by galileukim** [comment]
Duplicate of #197
