### ISSUE TITLE
Add option to download a .csv file with the data points used in the graphs

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#202]

**Comment by kannanv93** [comment]
<img width="938" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/f8e02983-2cba-497a-b260-46dc23dce58c">


@erwbg : is this good enough?

**Comment by kannanv93** [comment]
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/7383fc8d-3afa-4ca0-9f3f-54ca9a298a74)
 Completed

**Comment by kannanv93** [comment]
Works as expected
