### ISSUE TITLE
Incorporate new/updated manual data into the ETL process

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#207]
- [x] VDem (updated) [VDEM_1990_2022.dta]
- [x] Debt Transparency (added) [debt_transparency_2021-2022.dta]
- [x] GFDB Bank concentration (added) [GFDB_19902021.dta]
- [x] WDI (updated) [WDI_19902022_CLIAR.dta]
- [x] WBL (added) [WBL_19902022_CLIAR.dta]
- [ ] ------------------------------------------------
- [ ] IDEA Political Finance (under consideration. We should proceed in the meantime)

Manual imports are completed (for now). Final data (named above for each one) is in the CLIAR_dsahboard/data/cliar_data/data/input/ folder

**Comment by galileukim** [comment]
resolved with great thanks to @erwbg.
