### ISSUE TITLE
New methodology for estimating institutional family averages (on CTF and raw data)

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#208]
**Let’s look at the static first:**
For the static, as of now, the change we’re introducing is that we do not estimate family level CTFs that can be download in the data tab for SOE and Labor. (Benchmark_static_family_aggregate_download)
But nonetheless, the benchmarking graphs work just as they work now.

**For dynamic, it’s a bit more nuanced:**
For the benchmarking graphs in the dashboard, PFM and SOE are now excluded –ie., they’re not part of the dynamic benchmarking at all. (Benchmark_dynamic_indicator)
            -there’s still a bit of an open question on whether the Digital and Labor could work… at least at the individual level…
This is where it gets tricky, and welcome your suggestions for improvement (Benchmark_dynamic_family_aggregate)
            -No families: we do not produce family aggregates, neither on the overview benchmarking graph nor for download in the data tab
            -Yes: we continue as we do now
            -Partial: we produce the dynamic benchmarking in the graphs as well as in the family-level aggregates for download in the data tab, but only for even years.

It’s also important to note that we need to double check how things look in terms of coverage for Business and Service delivery once we have the updated data. For now, let us assume that “?” means Yes for the purposes of our initial pass. So we may need to revise something here and there, but the structure of including/removing some families will remain. 

**Estimates on Raw Data**
Until we finish the CTFs estimates, let us put a pin on the raw data estimates.

**Comment by galileukim** [comment]
I see the following issues in this new feature, that we need to address:

1. How do we differentiate between variables that are downloadable or not? We should use the `vars-control.R` for this ideally, but it is not clear to me how to implement that. We could establish a filter that reactively applies whenever a user downloads data, but we have to be careful.
2. How do we adjust the display for input buttons, depending on which institutional families are available for each indicator? It is not clear to me the logic of implementation in the app.
3. How do we accommodate the partial benchmarking in our logic? Should we consider creating a separate institutional family averages object? If not, how do we ensure that we have a proper convention to identify each one of these institutional family average columns? How will the app behave in the context of implicit missingness in data?

**Comment by galileukim** [comment]
Hi @erwbg, and including @kannanv93  for visibility:

1. This may be a confusion on my end then. My understanding was that there will be some family averages that will be displayed but not downloadable: have we eliminated that? Looking at your notes more closely, it seems that we did.
2. By input button I mean the drop-down menu. It's not clear to me whether family averages that are neither displayed nor downloadable are displayed.
3. Yes, the devil is in the details of implementation. Perhaps the missingness in odd years will address this, but we need to triple check this.

**Comment by galileukim** [comment]
@kannanv93, one issue I have identified is that the drop-down menu does not dynamically adjust to the list of family averages we have available for any given data. I would suggest reviewing the vars-control.R and seeing how we can adapt the family_names object (line 211) to a dynamic object. not for now, but this is important: it affected my user experience and had no idea why some family averages were showing up and not others.
