### ISSUE TITLE
UAT | graphs issues: figure overlaps with note

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#209]
@kannanv93: it seems we're having some issues with the graphs --mainly with overlap with notes (see examples below). This is not high priority, but we do need to address it soon so we can circulate the dashboard.

Bivariate correlation:
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/e19d6f71-a33b-4b61-ae07-f04c903e8c55)

World Map:
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/4cd39733-815c-45ad-99e1-66a2144935d1)

Time Trends:
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/b379646a-f096-4220-b614-387bef52bdd0)

**Comment by kannanv93** [comment]
<img width="1181" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/cdff3689-2f04-46ac-b870-d254e30307c4">

<img width="1181" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/4369c24b-28cb-4ff5-9b79-9fc6280ebb81">
