### ISSUE TITLE
UAT | Restrict "indicator definitions" table in Country bencharmking tab to benchmarking indicators only

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#213]
The indicator definitions table that is currently displayed in the benchmarking tab includes indicators of the family "(other indicators)".

Please restrict the table to only show definitions/source for:
--indicators that belong to "real" families (i.e., exclude "(other indicators)"
--indicators that are supposed to be benchmarked (i.e., exclude those that we classify as benchmarking==NO)

**Comment by kannanv93** [comment]
Filtered Variables displayed in Indicator Table
