### ISSUE TITLE
UAT | benchmmarking Notes show incorrect info/typos

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#220]
Looking at a simple static benchmarking (ARG vs OECD), identified the following 2 issues (see snapshot below)

- [x] At the end of the missing indicators paragraph there's a "200" which is a typo/bug. For some reason it appears on different results.
- [x] The last line reads "Family-level closeness to frontier is calculated by taking the average closeness to frontier for all the latest available indicators in each family." **It should read**: "Family-level closeness to frontier is calculated by taking the average closeness to frontier for the estimated indicators within each family."

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/2d5a7324-8863-4bc7-b2ae-9b5773ad9dee)

**Comment by kannanv93** [comment]
<img width="848" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/93a47618-180e-4835-a710-0ecd4ff50135">

Fixed all the above issues
