### ISSUE TITLE
UAT | issue with dynamic CTF change 

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#221]
There seems to be a typo in how the absolute change in CTF is calculated in the dynamic benchmark. This is most obvious in the case of the Climate Change family (see screenshot below):

It may have something to do with the fact that now the "oldest" possible year in the dynamic is 2014? The \delta CTF should be estimated as CTF in the latest year available - CTF in the oldest year available,

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/c2605060-082c-4676-83bb-8f4f77e26709)

**Comment by kannanv93** [comment]
@galileukim Looks like there is some data issue with Armenia. All average except the two shown above are all NA.


<img width="742" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/6178e563-8dcf-4b99-9a8b-70db7dbc63cd">
