### ISSUE TITLE
UAT | issues with ranked data + consider remove option to download data

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#223]
There are countries with missing data that get a ranking, for instance, Andorra and American Samoa. Ranking should be "missing" in those cases.
 
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/142b9b91-d578-44a7-a359-e2af4ffa33e1)

 
 
Also, the dynamic rank has the same problem and there are rankings of over 1000...

TEMP SOLUTION: to just to remove the option of downloading the ranking data in the data tab.

**Comment by kannanv93** [comment]
Temp Solution Implemented
