### ISSUE TITLE
UAT | Issues with Time-trends displaying "family-level" averages

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#225]
hi @kannanv93: let's put this as high priority to fix.

In the time trends options, which uses raw data, we get some a very weird result with family-level averages that should not be there.

FIX TO DO: as family averages in the time trend, we should only have the ones we compute as "global" dynamic ctf family averages. Which means, many families will be missing. In cases where a family is missing, it should *not* appear as an indicator in the drop-down list. 

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/b18eb3b6-aabb-4db4-a0cf-4dd8494e6955)

**Comment by kannanv93** [comment]
@galileukim  : FYI, need to check raw data

**Comment by kannanv93** [comment]
Remove family level average on time trends

**Comment by kannanv93** [comment]
<img width="796" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/72e4f4a0-522d-4da9-86e1-62a0f8a0a18f">

Removed Family Average from Time Trends
