### ISSUE TITLE
UAT 2 | Issues with "Show Group Median" option

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#231]
We need to edit (and potentially remove) the "Show Group Median" option.

The issue is that currently is showing "very unbalanced" estimates, so we need to stay away from that.

The main reason for keeping the "Show Group Median" option is to show the group medians when choosing/displaying custom groups. 

Can we "remove the show group median" option BUT make automatic the fact that when users choose custom groups, their respective medians get calculated and displayed by default?

**Comment by kannanv93** [comment]
<img width="1275" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/c445d788-4b34-490c-a66d-0003b6457628">

@erwbg : Removed Show Median and ensured when custom_groups are created, their median is also displayed. Please check and close the issue

**Comment by kannanv93** [comment]
@erwbg : please test UAT_2 and close the issue

**Comment by kannanv93** [comment]
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/2a045d7b-0c7d-4ee5-b204-81280baedd82)
Fixed Issue
