### ISSUE TITLE
UAT 2 | Issues with "Original Data"

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#232]
Two issues with "Original Data"

- [x] download is *not* working. (it's downloading an .htm)
- [x] labels need to be fixed. see picture below

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/1ed1c70d-9373-46e0-a468-23a62229547f)

**Comment by kannanv93** [comment]
@erwbg  : Are these indicators from Manual extraction or EFI ? For EFI data, which I prepared, I had added the Labels in R. If its Manual, I think it wasn't added. Please share the labels for missing indicators(less than 32 Characters). I can add it to the DataETL

**Comment by kannanv93** [comment]
@galileukim and @erwbg : Please see below that two Variables have same Var_name. 
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/56b482fe-671c-4bfe-8cba-650b1d96ae56)

This has created a conflict and italic part in the below code failed. Hence the download isn't working properly. We need to fix the variable_names(or rather db_variables).

  output$download_global_rds <-
    downloadHandler(
      filename = function() {
        paste0(input$data_source, "-", input$data_value, "-gbid-data.rds")
      },
      content = function(file) {
        browser()
        write_rds(
          browse_data() %>%
            _setnames(
              .,
              as.character(variable_names$var_name),
              as.character(variable_names$variable),
              skip_absent = TRUE
            ),_
          file
        )

**Comment by kannanv93** [comment]
1. Label issues fixed by using db_variables
2. download is not working : Updated Db_variables
   2.a Stata expects variable names to be less than 32. The highlighted ones are now trimmed to 32 characters.
<img width="290" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/12843285-ee49-40b1-be1d-7e8acc0c31a0">

@erwbg  : Please check UAT_2 and close this issue

**Comment by kannanv93** [comment]
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/82315c76-d49f-4aca-9b58-45a8e952dd98)

Fixed Issue
