### ISSUE TITLE
Robustness Static CTF

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#233]
Hi @galileukim. We need to create a few robustness estimations for the static CTF data. I'm thinking of starting with the following

- [x] same global frontiers, but instead of using 5-year avg, let us use the "latest" data point available in the 5-yr window

This would not be for the dashboard, but rather our own internal/analytical checks. Would you be able to create and share a database with both the "regular" static CTF and the "last-data"?

**Comment by galileukim** [comment]
this is done.
