### ISSUE TITLE
ETL: create principled approach for dropping small countries/territories

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#234]
it could start with just dropping 0% coverage. see how others (WGI, CPIA) do it. double check Cuba and North Korea.

**Comment by galileukim** [comment]
@erwbg Cuba and North Korea are dropped from the start. If we want to drop countries with no coverage for any indicators, we can do so. My understanding was that we wanted to keep the missingness explicit in our dashboard, and just signal that the country has no available data. What do you think?
