### ISSUE TITLE
UAT 2 | Percentile Rank is still having 0.5 bugs in Dynamic Graphs

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#236]
ARG vs OECD
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/feb080c4-341b-4713-af74-58428ea95ea7)

**Comment by kannanv93** [comment]
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/5dfae99a-3207-4e0e-ba81-d6acc9e35182)
Issue Fixed
