### ISSUE TITLE
UAT 2 | Fix legends in multiple base-country benchmarking

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#238]
Here's an example of a multiple-base country figure (from an actual application). 4 countries vs EU. And compare that to the one below, which was locally made by @gabrielvazdemelo.

It would be better to get closer to that original version; larger markers; and separate countries and ranking. 

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/af6ee37f-fc78-44a1-b9ac-27aa7f94f88e)

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/455e1a50-c5b6-4bb5-b627-762c48847895)

This is medium priority. So just adding it to our list of issues to get a better sense of the fixes we have on our list.

**Comment by kannanv93** [comment]
Adding additional information for reference.  The static(read as not interactive) plot with unique country and legends can be replicated. The issue crops up when static plot is converted to interactive_plot in the following lines in server.R

 ```
           data_family() %>%
              left_join(.,family_order,by=c('var_name'='family_name'))%>%
              arrange(country_name,family_order)%>%
              static_plot(
                base_country(),
                input$family,
                input$rank,
                dots = input$benchmark_dots,
                group_median = input$benchmark_median,
                custom_df = custom_df(),
                threshold = input$threshold,
                preset_order = input$preset_order
              ) %>%
              **interactive_plot**(
                input$family,
                plotly_remove_buttons,
                "static"
              )
```

<img width="833" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/bfd02911-bffc-4906-b0c1-401c2fb79eef">

**Comment by erwbg** [comment]
We discussed this today. The "static" graph works well because it gets downloaded at the Report. As such, we have decided the following: we'll put a pin on the dashboard graph/legends (leave it for future enhancement).

In addition, we have the following requests. @kannanv93 please take the lead here:

For the static plot, if possible
- [x] replace the coloring fill of the emerging, weak, strong with their respective colors instead of black
- [x] order them from weak, emerging, strong (instead of the order now which is alphabetical, it seems)

**Comment by kannanv93** [comment]
<img width="468" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/b467f167-b752-4079-923f-52331980a4fb">

Fixed this issue in report
