### ISSUE TITLE
UAT 2 | Issues with "data download" (missing dynamic CTF individual indicators)

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#240]
@kannanv93: just forwarded an email.

The issue is that individual-level indicators with dynamic CTFs that appear in the Dashboard graphs (rightly so) are then not available when downloading the dynamic CTF data. 

Based on the discussion today, we suspect it may have to do with the filters we have for family-level averages.

The decision to include dynamic CTF individual-level indicators to download should be based on the "Benchmark_dynamic_indicator" column (see below). The Dashboard and graphs are functioning as they should now, it's just a matter of ensuring that the individual-level dynamic CTF estimates are available to download as well (and not just some).

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/c78c5ba0-7cea-4954-913a-f07b5d3cc988)

**Comment by kannanv93** [comment]
@erwbg : The following is the code were the respective data is selected. Here global_data is CTF and CTF_dynamic computed as in the DataETL. So should we fix this in Data ETL or dashboard ?
`  browse_data <-
    reactive({
      data <-
        if (input$data_source == "Closeness to frontier (Static)") {
          global_data
        } else {
          if(input$data_source == "Closeness to frontier (Dynamic)"){
            global_data_dyn
          }else{
            
            raw_data%>%
              select(-ends_with("_avg"))
            
          }
          
        }`

**Comment by kannanv93** [comment]
Completed
