### ISSUE TITLE
UAT 2 | Fix "from best to worst" (not working) when choosing "rank instead of value".

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#241]
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/55a375c1-a00e-442b-b137-5c6793e7a8a4)

**Comment by kannanv93** [comment]
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/ae3e89e7-f19f-4d31-8182-e7e61899a055)

Fixed
