### ISSUE TITLE
Clean-up dashboard links (including in R-connect)

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#252]
We only want to keep 

https://datanalytics.worldbank.org/CLIAR/ ["official"]

and 

https://datanalytics.worldbank.org/cliar_dev/ ["our own dev version"]

@kannanv93, please delete the rest (specially from R-connect, to free up space there). And cliar_uat_2 is the latest, no? Can we push it to both "CLIAR" and "cliar_dev", please?

**Comment by kannanv93** [comment]
We have https://datanalytics.worldbank.org/CLIAR/ and https://datanalytics.worldbank.org/cliar_uat/. Do you want the dev version or uat version ? 

I have cleared the rest.

**Comment by kannanv93** [comment]
Private Links : 
http://w0lxprconn01.worldbank.org:3939/CLIAR/
http://w0lxprconn01.worldbank.org:3939/CLIAR_UAT/
