### ISSUE TITLE
Rename downloadable datasets 

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#254]
Rename current --> to --> new name

Closeness to frontier (Static)-Value-gbid-data --> "CLIAR Closeness to frontier (Static) data"
Closeness to frontier (Dynamic)-Value-gbid-data --> "CLIAR Closeness to frontier (Dynamic) data"
Original indicators-Value-gbid-data --> "CLIAR Original indicators data"

(@kannanv93: feel free to use - or _ or spaces between names as you see fit)

**Comment by kannanv93** [comment]
Issue Fixed
