### ISSUE TITLE
Improve [Cross-country comparison/Time trends] tab + bug with non-benchmarked data

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#255]
- [x] Re-order the order of operations: from (a) "Select indicator", "Select a base country" and "Select comparison groups" to (b) "Select a base country", "Select comparison groups" and then "Select indicator"
- [x] [For cross country] Remove "green dashed line on the right" 
- [x] Add a brief intro sentence saying: Data displayed is based on the CTF data (for cross-country) [QUESTION: what to do with non-benchmarked here?]. Data displayed in based on the original indicators (for time trends).
- [x] BUG: if I select "wage bill as % of GDP" (as an example of a non-benchmarked indicator), the server automatically disconnect. We need to figure out what's happening there

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/883c3558-8ba0-48b8-bbfe-0b4b4d02308a)

**Comment by kannanv93** [comment]
wage bill as % of GDP is not Benchmarked. Ideally, we should remove this indicator from the dropdown.

**Comment by erwbg** [comment]
Thanks, @kannanv93!

I think I'm ok removing the not-benchmarked indicators from the dropdown menu in the cross-country comparison.

BUT, we should keep the not-benchmarked indicators in the time-trends. 

Can we do that?

**Comment by kannanv93** [comment]
@erwbg: Its been updated. Non-Benchmarked are getting reflected in time trends. 

There seems to be problem in reordering the indicator to the last. Currently, the code follows a order were given an indicator, it identifies all countries for which the indicator is not NA. Then it updates the country dropdown with valid list of countries. If we have to change this order, we will need to implement the validation differently. First select country, identify list of indicators valid and update the indicators dropdown. 

Can you please confirm the same ? I can go ahead and make this change.

**Comment by kannanv93** [comment]
Additionally, there is a interdependencies in multiple tabs where an indicator selected in one tab is updated in all tabs. This causes issues when we have tabs specific for benchmarked indicators (like Country Comparison) and tabs common for all indicators (Time Trends). This was one of the reasons for the app to crash when selecting Wage %. I am currently disabling this option. We can discuss if we need this option for the application.

**Comment by erwbg** [comment]
Thanks, @kannanv93!

As discussed today, confirm the change in order and start with "base country". Let's forget about the interlinkages across tabs of the "indicators". However, if there has been a base country selected in the country benchmarking, sure, keep that as default, but in any case, the user should always be able to edit that option.

Also, we can leave all indicators, and have a very clear error message when such indicator is missing from the base country.

**Comment by kannanv93** [comment]
@erwbg : Deployed to datanalytics/CLAIR_UAT. Please check and report if any inconsistencies.
