### ISSUE TITLE
World Map tab enhancements

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#256]
- [x] There's no legend header when "original indicator" is selected as data source. Can we add a small legend header saying "Original indicator scale" or something along those liens?
- [x] Need to clarify data source, and time coverage: if original, are we also using the 2018-2022 average?
- [x] Can we increase speed? It's too slow, and that causes confusion as well

**Comment by kannanv93** [comment]
I have added a spinner wheel to show its loading. I will try to increase speed.

**Comment by kannanv93** [comment]
The following is the code in Code/05-map.rmd. Here for Raw data, we don't take any average but rather take the value corresponding to the latest year for which data is available. 

raw <-
  raw_indicators %>%
  select(
    -c(income_group, region)
  ) %>%
  pivot_longer(
    cols = 4:ncol(.)
  ) %>%
  filter(!is.na(value)) %>%
  group_by(country_code,name) %>%
  filter(year == max(year)) %>%
  pivot_wider(
    values_from = c(value, year),
    names_from = name,
    id_cols = country_code
  )

**Comment by erwbg** [comment]
> The following is the code in Code/05-map.rmd. Here for Raw data, we don't take any average but rather take the value corresponding to the latest year for which data is available:

That's totally fine. we just need to clarify/be explicit about it in the note in the bottom

**Comment by kannanv93** [comment]
@erwbg Please check the maps(dataanalytics/CLIAR_UAT)now and close this issue if it is working as expected

**Comment by erwbg** [comment]
Thanks, @kannanv93! Two things:

1. When we show the CTF, are we using the Static or the Dynamic CTF? This is important because depending on which one we need to edit the data "note" (which should be different that the data note when choosing original indicator).

2. We seem to have an issue when, for instance, select "Absence of Corruption Average" and "original indicator" (presumable, when we choose "family-level" averages, CTF and original indicators should be the same, no?)
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/023fb58f-828b-4af9-92ec-31026997c374)

**Comment by kannanv93** [comment]
1. We are using Static CTF and Not Dynamic.
2. Need not be, Taking average of 1,2,3 is 2 but taking average of original numbers which give 1,2,3 (For example: 1 (for 1 ), 1.5 & 2.5 ( for avg of 2) and 1 & 5 (for avg of 3) can give average of (1+1.5+2.5+1+5)/5 = 2.2.

I can recheck though.

**Comment by erwbg** [comment]
Thanks, @kannanv93!

1. Perfect. Let's clarify that in the notes then.
2. I think our CTF "family-level" averages as "the original indicator as well", because in a way, the "original" is CTF as well... that's why. Let's make sure they're the same, and double check the map. In the example above the scale/colors weren't working properly
