### ISSUE TITLE
BUG Dynamic benchmarking not working

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#257]
- [ ] showing "An error occurred. Data is missing for the selected base country."

- [ ] we also need to improve the presentation of graphs and summaries, including the report. @kannanv93 as you've worked on this issue before, could you propose a few suggestions here?

**Comment by kannanv93** [comment]
Can you please share screenshot for the above error ? I want to replicate the error from my side.

**Comment by erwbg** [comment]
This is for instance doing Argentina vs OECD, overview:

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/5e16e9e5-7fc4-45c1-8caf-56b6a22bee35)

**Comment by kannanv93** [comment]
I dont see a problem in UAT version. I will merge all these issues to main.
