### ISSUE TITLE
Data download tab: add a "loading" figure?

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#258]
In our data download tab, selecting a new dataset (specially when selecting the original) takes a bit of time.

Can we add a "loading figure" like the one we have when the report is being processed for download? (ie the one that says "Compiling report"? Instead of "Compiling report" it could read "Loading data").

@kannanv93 what do you think?

**Comment by kannanv93** [comment]
I have already implemented this. Closing this Issue
