### ISSUE TITLE
Fix cross-country comparison + Time trends (order + select indicator duplicate)

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#263]
We want fix the "Cross-country comparison" + "Time Trends". 

We want to have country base and country comparator first, then indicator. and remove the duplicate indicator button

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/2cae83a4-189a-461d-93eb-a4591b37ddaa)

**Comment by kannanv93** [comment]
Issue has been fixed.
