### ISSUE TITLE
Add new data for download to Data tab

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#264]
a.	CTF Static (Cluster-level aggregates only) --includes confidence intervals/sd
b.	CTF Static (All indicators) --includes cluster-level aggregates, but *not* confidence internals/sd
c.	CTF Dynamic (Cluster-level aggregates only) --includes confidence intervals/sd
d.	CTF Dynamic (All indicators)  --includes cluster-level aggregates, but *not* confidence internals/sd
e.	Original indicators --entire raw data (benchmarked + non-benchmarked)

@kannanv93: to subset the data and create (a) and (c) as the file size shouldn't be large at all.

For simplicity, allow direct download from the Data tab buttons (see below) directly in .CSV (we'll explore different formats later).
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/99324408-280b-47e1-87ba-585221169001)

**Comment by kannanv93** [comment]
Issue fixed.
