### ISSUE TITLE
Issues to fix when multiple base-countries are selected

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#265]
We have some issues to improve when multiple-base countries are selected:

REPORT
1. We need create a separate dynamic plot function for this case. Two key features:
1.1. Need to improve the way key change metrics are displayed --which are thought for single base countries. Could they be displayed on the side for example? Any other ideas?
1.2. The lines connecting the dots do not work properly when multiple countries are plotted. See figure below
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/55fc8fc3-8744-4b62-9d2d-c94e10fca8e7)

2. More generally, it seems the report writes itself as if it is only about the "first" Base country (alphabetical). So all the paragraph describing indicators and results are for the first country only. We need to add additional paragraphs IFF there's a n-th country. I have seen reports for up to 4 countries, so that should be our max.

**Comment by kannanv93** [comment]
@erwbg  : we don't allow multiple base countries for dynamic benchmarking.  Can you share the inputs to recreate such a graph. I tried few combinations and wasn't able to replicate one like this. 

Please use dataanalytics/clair_uat version.

**Comment by erwbg** [comment]
Hi @kannanv93!

One additional issue to improve, in the Dashboard graphs: when we click "Show notes" we see the following. This is an example from Argentina + Croatia vs. OECD countries.

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/4b5f9c42-563b-4832-b429-eb6132b7f1d4)

We have some repetition, and then the list of missing vars seems like it corresponds to the first base country (it would be weird that Croatia and Arg have the exact same missing vars, but it could be).

I think the structure should read:

"Base country 1, Base country 2, Base country X, compared to OECD members.

The following indicators are not considered because the base countries have no information or because of low variance: [list the combined the list]

**Cluster**-level closeness to frontier is calculated by taking the average closeness to frontier for the estimated indicators within each **cluster**."

Note that in the indicator para we talk about "the base countries". If you want to make it general it can read: "the base country (or countries)"
Note that in the last line, it should read "cluster" instead of "family".

**Comment by kannanv93** [comment]
The note function has been updated. Please check and close issue. @erwbg

**Comment by erwbg** [comment]
Thanks, @kannanv93!

Looks great. Two small edits in the last sentence: (i) cluster-level instead of family-level and (ii) dot (.) missing at the end. the last sentence should read 

"Cluster-level closeness to frontier is calculated by taking the average closeness to frontier for the estimated indicators within each cluster."

instead of 

"Family-level closeness to frontier is calculated by taking the average closeness to frontier for the estimated indicators within each cluster"

**Comment by kannanv93** [comment]
Issue fixed. Notes updated
