### ISSUE TITLE
Improvements in Country-Benchmarking

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#266]
@kannanv93, there are a couple of improvements that we should do in the Country Benchmarking tab, basically using things you did before:

1. Restore "Rank indicators from best to worst" as an option ONLY IF "Show rank instead of value" is selected.
now it looks like:
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/164bfe53-7a37-4961-a416-41ba9d12c044)
but we want it to look like before:
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/41ea9d86-0310-4d79-acb9-e5afb7977469)

2. Now, "Show list of countries" *disappears* IF "Create custom groups" is selected. Ideally, instead of having the "Show list of countries" disappear, we would have it in gray & without being able to select it. Does it make sense?
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/8a79d276-32a7-433a-b347-80f596a68681)

**Comment by erwbg** [comment]
@kannanv93 just a quick follow-up on the "graying" of "Rank indicators from best to worst"

now, when you first open the dashboard and country benchmark tab, it actually appears as "gray", but the moment for example one selects a base country, it turns on "black". And we only want this when "Show rank instead of value" is selected :)

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/443e16e6-545a-4bda-a145-b6a94ab652a8)

**Comment by kannanv93** [comment]
Issue has been fixed.
