### ISSUE TITLE
Bug in Static benchmarking

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#267]
@kannanv93, we have the following bug. This is from West Bank and Gaza vs. MENA.

It seems that the business environment cluster only has one available indicator. Fine. But then, the scores between that one indicator and the "cluster average" are very different. Remember we had done quite a bit of re-structuring to ensure that the dashboard "cluster averages" would be totally reactive to the base country+comparators and their available data? As such, the business env avg *must* (by construction) be equal to the indicator available (as the business env avg should represent the avg of the available indicators and comparators for any given case).

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/1ce633dd-9345-4aba-b0d4-e96e2b55fcd6)

**Comment by kannanv93** [comment]
<img width="948" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/4f55c27c-6a41-4e52-8da9-59412cc13b19">

@erwbg  : I checked this case. While calculating average there are two indicators. But we remove variables which have low variance using the below code. 

  # Remove indicators where there is too little variance
  low_variance_indicators <-
    quantiles %>%
    filter(country_name == base_country & q25==q50) %>%
    select(variable) %>%
    unlist

That removes the variable wb_wbl_entrepreneurship from display. please let me know what should be the ideal fix for this.

**Comment by erwbg** [comment]
Thank you so much for this @kannanv93! 

This is super useful. Actually, we need two fixes (one for this, one for the little variance criterion):

1. Little variance should be q25==q75 instead! We want percentile 25 to be equal to percentile 75th, not the median.
2. for the cluster average estimation it means that we should remove the "low_variance_indicators" when we estimate the cluster_avg

Thanks again!

**Comment by kannanv93** [comment]
@erwbg :

<img width="421" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/c9a1249e-d053-45cc-855d-5bd71acc5673">

What should be the comparsion for Terciles ?

**Comment by erwbg** [comment]
Thanks, @kannanv93!

I think I'm a bit confused by this. Because the "removing indicators with low variance" should have nothing to do with whether we then use "default" or "Terciles" on the analysis... so I think we should make sure that's the case: it may be easier to chat :) will send a calendar invite

**Comment by kannanv93** [comment]
@erwbg  This issue has been fixed. Please test and close the issue if there are no bugs
