### ISSUE TITLE
Bug in report: issues with cluster average in cluster-specific graph

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#268]
hi @kannanv93, found the following issue:

Take ARG vs OECD. Absence of corruption family:

this is the graph that get's produced in the Dashboard:

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/4ee04507-b8af-4d05-af16-2179a79756d7)

and this is the graph that gets produced in the Report:

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/642a126f-3ed1-4111-bf95-7bac3f329261)

Comparing it with the "Overview" graph in both cases, it seems that the estimation of the "Cluster-level AVG" in the "cluster-specific" graph in the REPORT, is off. I presume that we corrected the way the we estimate the cluster-level avg (it could be our latest modification in low-variance indicator) and it is not yet properly reflected in the report.

Can I kindly ask you to check this? many thanks!

**Comment by erwbg** [comment]
ADDITIONAL ISSUE @kannanv93 

the same problem is presented in the PPT REPORT, with the *addition* that some cluster-level averages are not displaying (presumably because those are the ones where we don't estimate a 'global' family avg). We need to double-check the code and make sure that the reports also estimate the cluster-level avgs and take into account low-variance indicators in line with recent fixes

**Comment by kannanv93** [comment]
Issue has been fixed. Additionally in PPT report, the dynamic plot is commented. Needs more formating as it doesn't fit the PPT dimensions.
