### ISSUE TITLE
Bug in report: description of results

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#270]
hi @kannanv93, i'm reading a simple report, Argentina vs OECD, and we have a bug in the description of indicators, both when describing the whether clusters/indicators are above 0.5 and when describing their classification. Can you please review the code in the text, please? Many thanks!

for example:

Static Benchmarking
The static analysis of Argentina institutions was performed on a basis of 109 available indicators that are grouped in 13 institutional clusters.
0 institutional families out of 13 exhibit a proximity to the frontier greater than 0.5, which means that 0 institutional clusters are closer to the world’s best performers. In relative terms, as shown in Figure below, scores for 12 institutional clusters (Absence of Corruption, Climate Change and Environment Institutions, Digital and Data Institutions, Public Human Resource Management Institutions, Labor and Social Protection Institutions, Justice Institutions, Business Environment, Public Finance Institutions, SOE Corporate Governance, Service Delivery Institutions, Social Institutions, Transparency and Accountability Institutions) indicate weak performance, 1 of the clusters (Political Institutions) are classified as ‘emerging’ and clusters () demonstrate a strong performance.

Country overview
 
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/c6a53bb2-b0bc-40b5-a3bd-30c04278ece8)

**Comment by kannanv93** [comment]
Updated Text. 
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/39fd2d5d-e342-46d6-96be-fdad3d5a2949)

@erwbg : please check and let me know if we still need restructuring.

**Comment by erwbg** [comment]
Thanks @kannanv93! this looks great. quick question: is it possible for the case of the last sentence to have "and 0 clusters (none) demonstrate a strong perofrmance"? That is, how to deal with 0's? This is gonna be a typical case actually (e.g., I'm thinking Uruguay vs LAC has 0 clusters with weak performance), so would be great to have it general

**Comment by kannanv93** [comment]
Fixed Issue
