### ISSUE TITLE
HIGH PRIORITY "Original indicators" data does not match the entire indicators listed in the metadata_dev

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#271]
We have a few *hundreds* indicators missing... let's make this high priority

**Comment by kannanv93** [comment]
@erwbg : please check. I have updated the files and deployed the updated version. Please confirm and close this issue.

**Comment by erwbg** [comment]
@kannanv93: thanks! I see the "original" now data has 417 indicators, but not 437 as per metadata_dev. Is this because of the duplicates you mentioned in the email? (Need to go over that in detail). Just to understand if the two are linked or not

**Comment by kannanv93** [comment]
Looks like these indicators are missing. Checking the data process now 


<img width="282" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/820c97ee-efb6-44e2-a3f8-31474cb40829">

**Comment by erwbg** [comment]
Thanks, @kannanv93!

**Comment by kannanv93** [comment]
For few of them, the status says removed. Hence, while converting from metadata_dev to db_variables, these variables have been removed. 

<img width="448" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/1ae63d50-1915-4c6e-a017-1339c9ab8286">

**Comment by erwbg** [comment]
We discussed this --and it is also in the email to @galileukim earlier today 

The "status" column in the metadata *should not be a filter*. ALL variables indicators in the metadata_dev should be added to the "master dashboard" data... and the filter for benchmarking begins with the "CTF Benchmarked" column. 

We need to fix this ASAP. If you want, change the name of the status column to "history note" or something so it doesn't create any further confusion please

**Comment by kannanv93** [comment]
What is the source for these three indicators ?. Missing out only these three now. 
heritage_businessfreedom`, `heritage_investmentfreedom`, and `heritage_financialfreedom

**Comment by kannanv93** [comment]
@erwbg : Closing this issue as all indicators are present in CLIAR_UAT. Please reopen if need be.
