### ISSUE TITLE
URGENT: issue with "Absent of Corruption" variables (missing)

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#272]
hi @kannanv93, we have a serious issue.

We're missing several variables in the Absence of Corruption cluster.

I can only infer that this is because the "latest" metadata_dev / manual and EFI data update has not worked properly. We have the same issues with the non-benchmarked data, but it's urgent that we fix this.

Because of this, it is not clear to me whether the latest CTF are properly done. @galileukim: would you be able to confirm whether this is the case? In the dashboard I only see 2 indicators for absence of corruption... and we need to know if it's just the dashboard or it is also in the entire CTF calcs.

many thanks!

**Comment by kannanv93** [comment]
@galileukim : I looked into this. Looks like the latest metadata_dev is causing this issue. Please re-share the updated db_variables file for me to trigger the data pipeline again.

**Comment by kannanv93** [comment]
@erwbg : please check. I have updated the files and deployed the updated version. Please confirm and close this issue.
