### ISSUE TITLE
Cross-country tab enhancement: allow for raw score option in addition to CTF score

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#274]

**Comment by kannanv93** [comment]
Hi @erwbg, Cross Country tab is a bar plot with one CTF value. 
<img width="917" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/267a7c2f-328c-459f-82ea-b9873205d75e">

If we need to add the raw data, the data spans at year level, which eventually needs to be represented as line plot, which is no different from the time trends plot for the same indicator as shown below. It will just be a duplicate copy if we add raw score to cross-country
<img width="873" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/c8c4c23f-796a-450e-baa2-2e131b88104a">


Please let me know how to proceed

**Comment by erwbg** [comment]
Thanks, @kannanv93!

for the cross-country tab bar plot "raw data" option we should follow the same procedure from the World Map --that is, when using raw data, use the "latest year" available. What do you think?

**Comment by kannanv93** [comment]
@erwbg : Updated UAT. Please check and close this issue.

**Comment by erwbg** [comment]
thanks, @kannanv93! this is great!

quick question: can we allow the bar plot without imposing the requirement of adding comparison groups? it's fine if it's too complicated, but I'd like to avoid the user being "confused" by choosing a base country and not seeing a bar plot.

let me know what you think. we can discuss later if easier

**Comment by kannanv93** [comment]
Issue Fixed
