### ISSUE TITLE
BUG/ENHANCEMENT NEEDED IN DATA TAB: (i) one with "select countries", and (ii) another one with "select groups to include".

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#276]
A few things: (i) one with "select countries", and (ii) another one with "select groups to include".

(i) one with "select countries"
After doing a country-benchmarking, when going to the data tab, and looking at "SELECT COUNTRIES TO INCLUDE", we get 3 options: 'all', 'base country only', and 'base country+comparators.'

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/313f36a5-fdd7-43d0-94e4-6cf84161a7d8)

The issue is that if users go directly to the data tab, they will only see the "All" option. This is confusing. We should keep the 'base country only' and 'base country+comparators' as well --but we keep them in gray/not clickable unless users have selected them. Does that make sense?

(ii) "select groups to include".
second point is that examining the "select groups to include", i'm not so sure what's the purpose of this now. It seems redundant. Moreover, it has the option of "none"... which is confusing again. I would suggest that we remove this option... but please let me know what you think?

**Comment by kannanv93** [comment]
Issue resolved. Please reopen if need be. @erwbg
