### ISSUE TITLE
[Indicator labels] Shorten indicator labels to improve visualization in graphs

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#277]
@kannanv93, we should have shorter indicator labels just for the visualization of graphs.

Example in overview: "Public Human Resource Management Institutions" --> "Public HRM Institutions"

What's the best way to do this? Should we add an additional column to our metadata_dev / db_variables?

**Comment by kannanv93** [comment]
@erwbg : please check if this solves the issue. If it does, please close the issue.

<img width="1242" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/a4b7f2d3-3a01-4f66-ac9f-9835af9f0d44">

**Comment by kannanv93** [comment]
@erwbg : please reopen if need be. For now closing the issue.
