### ISSUE TITLE
Add "Description" and "Source" to cluster-level averages in "Indicator definitions"

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#278]
Currently, the dashboard displays NAs in "Description" and "Source" of cluster-level avgs

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/be2f7edc-034c-49e0-a079-3ffe85a59058)

Not sure where's the best place to add (maybe manually in the ETL code where averages are created?), but I'd simplify and add the following description and source for all cluster-level averages:

Description: "The cluster-level average is an unweighted average of the (corresponding and available) indicators of this cluster. See Methodological note for details on the inclusion criteria."

Source: "CLIAR"

To make it easier, I'm suggesting a definition that's accurate enough to look good on the dashboard, but broad enough such that it encompasses both the "global" and the "benchmarking" avg... which I feel would confuse most users if explained in detail.

**Comment by galileukim** [comment]
Hi @erwbg thank you for this. I would suggest removing the wording on available because we only compute the average if all indicators are available for the cluster. What do you think?

**Comment by erwbg** [comment]
>  because we only compute the average if all indicators are available for the cluster.

Thanks, @galileukim, @kannanv93 . That is not quite correct... that's the difference between the "global CTF cluster avg" and the "benchmarking CTF cluster avg". For the actual benchmarking (i.e., overview graph) we always compute the average --regardless of the number of indicators available, and as such, **it's a function of available indicators in that given set of base country/comparator group.**

That is why, technically, we should have different definitions of cluster averages (e.g., the one in country-benchmarking should differ from time trends). But I'm afraid this may lead to confusion (as you can tell)... which is why I suggested the above referenced wording. Any thoughts on how to make this clearer without risking mixing the definitions?

**Comment by galileukim** [comment]
I see, thank you for clarifying. That's good to know: and the fact that I myself was confused means that we have to be clear, as you note @erwbg. What about this? 

Definition: The cluster-level average is an unweighted average of the corresponding and available indicators for this cluster. Indicators selected for cluster-level averages vary depending on the type of benchmarking. See Methodological note for additional details.

**Comment by erwbg** [comment]
Thanks, @galileukim!

that definition is fine! the one thing that makes a bit of noise is the being explicit about "the type of benchmarking" --as I'm not sure if that would confuse someone reading that definition in the "time trends" graph. Basically, i was going sideways being so explicit by making reference to "corresponding" indicators before. But I'm totally fine either way ;) Once you make the final edit, please go ahead and close the issue :)

**Comment by galileukim** [comment]
Sounds good @erwbg. Then let's maintain your wording and avoid confusion. I have removed the wording on type of benchmarking and edited for clarity, switching from available to included to connect directly to our wording on inclusion criteria. This is our final description:

_The cluster-level average is an unweighted average of the corresponding and included indicators of this cluster. See Methodological note for details on the inclusion criteria._

**Comment by erwbg** [comment]
@kannanv93: the updated description and sources are not appearing in the country benchmarking. Could you please double-check what's going on? Thanks!

**Comment by galileukim** [comment]
The changes should be merged into CLIAR_UAT. The pull request is still pending.

**Comment by kannanv93** [comment]
Branch merged and issue resolved.
