### ISSUE TITLE
[Time-trends] Bug when adding income-group averages

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#282]
these are time trends graphs for indicator "democracy status" from BTI

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/d5c9130e-a413-4e36-8fa5-25ed4e86389e)

this is after adding another group
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/dc952aef-9509-41cc-8f9b-349796267ec0)

no issue when adding countries
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/f78d8f64-6c18-4d9d-80ff-44de1eb63c97)

**Comment by kannanv93** [comment]
<img width="865" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/558e9eee-3e32-4a19-b9f7-c497fe8c9f62">
Issue fixed.
