### ISSUE TITLE
Improve Static Benchmarking Overview labels

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#283]
@kannanv93, we'd like to try the following to improve the visualization of the Overview Static Benchmarking graph:

1. As a lot of the space is used by the word "Institutions" in many of the clusters, could we remove the word "Institutions" for those clusters that have it, and maybe add some sort of y-axis label that reads "Institutions" or something along those lines?

Note that the "removing of Institutions" from the cluster name would only be for this graphs, and thus, it should not be reflected anywhere else.

Please let me know what you think. Many thanks!

**Comment by kannanv93** [comment]
Updated 
<img width="860" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/4c206f5d-7ec5-4f13-91a6-d528978e0437">

**Comment by erwbg** [comment]
Thanks, @kannanv93!

Two issues, in order of relevance:

1. Now, for some reason, the "order" is wrong. We want to make sure we keep using the "family order"

2. Is there a way to add a vertical text/label to the left that reads "Public Institutions" or something like that? Like "Closeness to frontier" appears on the x-axis, but on the y-axis, and vertical.

**Comment by kannanv93** [comment]
Updated the graphs

<img width="913" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/df59d331-746f-43ce-8899-da04d279b6ec">

<img width="926" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/a2fa8a2b-e04e-4672-a7e1-bc508a61e937">
