### ISSUE TITLE
ADD NEW PUBLICATION TO PUBLICATION TAB

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#284]
hi @kannanv93: can you please add the following publication to the publication list? Following the same structure --that is, add the header/type "Country Climate and Development Report (CCDR)"; include the image, and all that

Democratic Republic of Congo (DRC) Country Climate and Development Report (CCDR)

https://openknowledge.worldbank.org/entities/publication/b1dd27cc-249f-4380-9b73-80cb8f695a43

many thanks!

**Comment by kannanv93** [comment]
Added document to publications tab
