### ISSUE TITLE
Customizing colors for countries in time-trends/bar plots?

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#287]
@kannanv93: there are some requests to have a function to "customize" colors/add more colors to the countries in time trends/bar plots. This is not a priority, but would be good to know if there are any "quick alternatives" where people can click and choose a color, or have an option where every single country has a different color vs the current option as we have it now?

**Comment by akhaterwb** [comment]
I added a color selector on a recent update.
