### ISSUE TITLE
CLIAR_UAT: graphs getting collapsed

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#290]
Hi @kannanv93! I was playing a bit with the dashboard: ARG vs LAC

and on the static graph i see something like

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/a830d91a-77aa-4492-b3ad-1b49ad770cd8)

and dynamic is

![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/9372bbdc-089b-46d3-8401-adcc1744c9dd)

Can you please give it a go at trying to see what we can do with the crunching?

**Comment by kannanv93** [comment]
This is because of length of image. I will increase the image size and this should get fixed.

**Comment by kannanv93** [comment]
Issue has been fixed
