### ISSUE TITLE
The Pipeline does not create 'closeness_to_frontier_confint_static.rds' that is required to run the app.

### ISSUE THREAD

**Issue by akhaterwb** [worldbank/institutional-assessment-dashboard#301]
The Data prep pipeline found in the 'code' section of the repo seems to work without error, but when I attempt to launch the server from the code in the 'app' section, I encounter the following error:

> Warning in readRDS(con, refhook = refhook) :
>   cannot open file 'C:/Users/wb630868/Desktop/Git_Repos/institutional-assessment-dashboard/app/data/closeness_to_frontier_confint_static.rds': No such file or directory
> Error in readRDS(con, refhook = refhook) : cannot open the connection 

I tried finding the place in the pipeline that produced the 'closeness_to_frontier_confint_static.rds' I went to the file '04-ctf.Rmd' and I found where various closeness_to_frontier rds's were being generated, but I didn't see any line that produced that particular file.

I am not a contributor yet, so I am tagging @galileukim and @kannanv93 as I cannot assign this.

**Comment by galileukim** [comment]
Hi @akhaterwb thank you for raising this. Which file on the `app` folder requires the *_confint_static.rds file?

**Comment by ileanamarroquin** [comment]
I am also experiencing a similar issue to this one when running the 'global.R' on the app.proj.  Here is the text that says that 'family_order.csv' file is missing from the app/data folder.

>  shiny::runApp()
Warning in file(file, "rt") :
  cannot open file 'C:/Users/wb622595/gitHub-repositories/institutional-assessment-dashboard/app/data/family_order.csv': No such file or directory
Error in file(file, "rt") : cannot open the connection

**Comment by akhaterwb** [comment]
This issue was caused by a call for this file in the global.R file. The file it needs is not used in the current version of the dashboard, nor is it generated by the pipeline, so I commented it out and it should no longer be an issue.
